### PR TITLE
pseudo code for equivalence

### PR DESCRIPTION
**Pull request by bbarker**
Note: this doesn't parse, not sure why.

Also I understand everything you pointed out in the prior discussion. though how to show one dataprop implies another is maybe not so obvious to me as yet.

Additionally I realized I should probably add a base case...

### CODE REVIEW

**Comment by githwxi** [comment]
I tried this one. It is actually quite involved:

https://github.com/githwxi/ATS-Postiats-contrib/blob/master/projects/MEDIUM/PEULER/P2/P2-hwxi.dats

**Comment by bbarker** [comment]
Yes, I think that is a little much for me at the moment, even for reading. I've updated the pull request to have a dats file; I'm not trying for a strong proof, just to get used to this style of coding.

I'd like to know how to get the following line to parse correctly in P2-bbarker.dats

```ats
prval pf0 = MYSUM(n2, n1, t(* should be 2 here *))
```

I.e., making the static variable available in a function body. I'll try to add to the wiki, maybe in thedependent types section.

**Comment by bbarker** [comment]
Also, please don't feel obligated to merge my crappy code - I was merely
using this as a convenient way to show changes.

On Mon, Feb 2, 2015 at 12:48 PM, Hongwei Xi <notifications@github.com>
wrote:

> Merged #3 <https://github.com/githwxi/ATS-Postiats-test/pull/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/githwxi/ATS-Postiats-test/pull/3#event-228679794>.
>



-- 
Brandon Barker
brandon.barker@gmail.com

**Comment by githwxi** [comment]
Okay, I removed P2-bbarker.

I added a non-tail-recursive one:

https://github.com/githwxi/ATS-Postiats-contrib/blob/master/projects/MEDIUM/PEULER/P2/P2-hwxi.dats

This one is tail-recursive:
https://github.com/githwxi/ATS-Postiats-contrib/blob/master/projects/MEDIUM/PEULER/P2/P2-hwxi-2.dats

**Comment by githwxi** [comment]
>>As for tail recursion, I thought my 'loop' within mysum is tail recursive.

Yes, your nopf-version is tail-recursive.

**Pull request merged**
